language: python
python:
  - 2.5
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - pip install -r requirements/travis-ci.txt
  - pip install -q -e . --use-mirrors
script:
  - python runtests.py
  # - python setup.py test
